myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pmapp.urls')),
]

#画像ファイルの保存場所の設定
from django.conf import settings
from django.conf.urls.static import static

# 画像を読み込むための処理　　　画像フォルダの場所を探す
# DEBUG = True （settings.py) 実際の環境ではFalseにしないとエラー文が表示されてしまう。
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pmapp/urls.py
from django.urls import path, include
from . import views

# vies.pyと表示のURLを紐づけるファイル
app_name = 'pmapp'

urlpatterns = [
    # これがないと最多尾が表示されない　vies.pyとHTNLの関係が定義されていないから
    # ’’がHTMLを示す
    # views.クラス名(views.pyで定義したもの)
    # as_viewはクラスベースの汎用ビューを使う時に書く。
    path('', views.Index.as_view(), name='index'),
    # 一つ目の引数はURL  nameはリンクを使う時の名称
    path('post_create', views.PostCreate.as_view(), name='post_create'),
    # <int:pk> int・・・整数値　pk・・・primary key 1から順にカウントアップされているID
    path('post_detail/<int:pk>', views.PostDetail.as_view(), name='post_detail'),
    # PostUpdate用
    path('post_update/<int:pk>', views.PostUpdate.as_view(), name='post_update'),
    # Djangoでは削除の場合、一旦確認が入る。　（本当に削除してもよろしいですか？）
    path('post_delete/<int:pk>', views.PostDelete.as_view(), name='post_delete'),
    # PostList用
    path('post_list', views.PostList.as_view(), name='post_list'),
    # LikeList用
    path('like_list', views.LikeList.as_view(), name='like_list'),
    # MusicList用
    path('music_list', views.MusicList.as_view(), name='music_list'),
    # PhotoList用
    path('photo_list', views.PhotoList.as_view(), name='photo_list'),
    # Login用
    path('login', views.Login.as_view(), name='login'),
    # Login用
    path('logout', views.Logout.as_view(), name='logout'),
    # SignUp用
    path('signup', views.SignUp.as_view(), name='signup'),
    # Like  defで作った関数は、as_view()なくていい  like_addのURLが呼び出された時に
    # vies.pyのLike_addが動き出す  ex)like/6
    path('like/<int:post_id>', views.Like_add, name='like_add'),
    # カテゴリーリスト
    path('category_list', views.CategoryList.as_view(), name='category_list'),
    # アーティストリスト
    path('artist_list', views.ArtistList.as_view(), name='artist_list'),
    # カテゴリー詳細ページ  ex)category_detail/news
    path('category_detail/<str:name_en>', views.CategoryDetail.as_view(), name='category_detail'),
    # 検索結果ページ
    path('search', views.Search, name='search'),
    # 検索するページ
    path('search_form', views.SearchList.as_view(), name='search_form'),
    # タグ新規作成ページ
    path('tag_create', views.TagCreate.as_view(), name='tag_create'),
    # コメント
    path('comment/create/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'),
    #カレンダー
    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path('mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'
    ),
    path('library', views.Library.as_view(), name='library'),
    path('mypage', views.Profile.as_view(), name='mypage'),
]

pmapp/models.py
from distutils.command.upload import upload
from ftplib import MAXLINE
from django.db import models
from django.contrib.auth.models import User

# カテゴリーテーブル
class Category(models.Model):
    name = models.CharField('カテゴリー名', max_length=50)
    # カテゴリーの英語名をURLに使用
    name_en = models.CharField('カテゴリー名英語', max_length=10)
    created_at = models.DateTimeField(auto_now_add = True)
    update_at = models.DateTimeField(auto_now = True)

    def post_count(self):
        n = Post.objects.filter(category = self).count()
        return n

    def __str__(self):
        return self.name

# 音楽ジャンルテーブル
class Genre(models.Model):
    name = models.CharField('音楽ジャンル名', max_length=50)
    # 音楽ジャンルの英語名をURLに使用
    name_en = models.CharField('音楽ジャンル名英語', max_length=10)
    created_at = models.DateTimeField(auto_now_add = True)
    update_at = models.DateTimeField(auto_now = True)

    def post_count(self):
        n = Post.objects.filter(genre = self).count()
        return n

    def __str__(self):
        return self.name

# タグテーブル
class Tags(models.Model):
    name = models.CharField('Tag名', max_length = 50, blank=True)
    # タグ名の英語名をURLに使用
    name_en = models.CharField('Tag名英語', max_length=10)
    created_at = models.DateTimeField(auto_now_add = True)
    update_at = models.DateTimeField(auto_now = True)

    def post_count(self):
        n = Post.objects.filter(tag = self).count()
        return n

    def __str__(self):
        return self.name

# データベース内のテーブルを定義するファイル
# Postモデルを定義
# Postテーブル
class Post(models.Model):
    # ForeignKey ＝ 外部キー（他のモデルと紐づいていることを意味する）
    # Djangoでは、model Userを定義していなくても元々持っている。
    # on_delete=models.PROTECT  もしUserに紐づいたPostがあればデータベースから削除できない
    author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False)
    # 文字列のField １行の時に使う
    # max_lengthを書かないと必ずエラーになる。
    # 半角全角関係なく50文字まで入るようになっている。
    title = models.CharField('タイトル', max_length = 50, blank=False)
    # TextFieldは複数行　※max_lengthはなくても良い。
    content = models.TextField('内容', max_length = 1000, blank=False)
    # 'Category'はCategoryモデルクラスと紐づいている
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    # 'Genre'はGenreモデルクラスと名前と紐づいている
    genre = models.ForeignKey(Genre, on_delete=models.PROTECT)
    # 'Tags'はTagsモデルクラスと紐づいている
    tag = models.ForeignKey(Tags, on_delete=models.PROTECT, blank=True, null=True)
    # サムネイル
    thumbnail = models.ImageField(upload_to='images/', blank=True)
    # 写真を撮ったスポット
    spot = models.CharField('写真スポット', max_length = 50, blank=True)
    #曲名
    music_title = models.CharField('曲名', max_length = 50, default='', blank=True)
    #アーティスト名
    artist = models.CharField('アーティスト名', max_length = 50, default='', blank=True)
    # 音楽ファイル
    music = models.FileField(upload_to='music/', blank=True)
    # 曲ワンフレーズ どこまでが著作権になるかわからないので文字数は１５文字で制限
    music_phrase = models.CharField('歌詞ワンフレーズ', max_length = 15, blank=True)
    # YouTubeのMVリンクURL
    youtube_url = models.URLField('YouTubeのURL', max_length = 30, blank=True)
    # 日付タイムスタンプ　自動的に今の時間を追加
    created_at = models.DateTimeField(auto_now_add = True)
    # 更新された時に今の時刻を設定
    # 更新された時以外は何も入らない
    update_at = models.DateTimeField(auto_now = True)
    # 更新された時以外は何も入らない
    date_at = models.DateField(auto_now_add = True)

    def like_count(self):
        n = Like.objects.filter(post = self).count()
        return n

    # Postを参照する時にタイトルを使って参照する。
    # strはstring文字列の略
    # self.idの時は__int__
    def __str__(self):
        return self.title

# お気に入り用のモデル
class Like(models.Model):
    # related_name="posted_user"
    post = models.ForeignKey(Post, verbose_name="投稿", on_delete=models.CASCADE)
    post_pk = models.IntegerField(verbose_name="投稿ID", blank=True)
    user = models.ForeignKey(User, verbose_name="Likeしたユーザー", on_delete=models.PROTECT)

#1対多のリレーションを実現するコメントモデル
class Comment(models.Model):
    text = models.TextField('本文')
    target = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='対象記事')

pmapp/views.py
from ast import Delete
from re import template
from django.views import generic
from django.shortcuts import render, resolve_url, redirect
from django.http import HttpResponse, HttpResponseRedirect
# Djangoで準備されているViewをインポート
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView
from .models import Post, Like, Category, Comment, Genre, Tags
from comment.models import Comment
from django.urls import reverse_lazy
from .forms import PostForm, LoginForm, SignUpForm, SearchForm, TagsForm, CommentCreateForm
from comment.forms import CommentForm
# Djangoが用意したライブラリmessages
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q  #QはOR条件
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import redirect, get_object_or_404
from . import mixins
import datetime

# UserPassesTestMixinを継承してオリジナルのクラスを作成
class OnlyMyPostMixin(UserPassesTestMixin):
    # 例外処理を行うかどうか = True
    # 判定はUser
    raise_exception = True

    def test_func(self):
        # 今開いている記事をpostに入れる (pkを使う)
        post = Post.objects.get(id = self.kwargs['pk'])
        # 今開いている記事の筆者と今ログインしている人の名前が一致しているかどうかの判定
        return post.author == self.request.user

#Djangoは大文字と小文字を区別
#defではなくclass
# views.pyで作ったクラス名はurls.pyでも使うのでクラス名に注意！
# クラスベース汎用ビュー 他にCreateView（作成）, UpdateView（更新）, DetailView（削除）, ListView（一覧）がある。

class Index(TemplateView):
    # templatesフォルダにあるHTMLを指定。
    template_name = 'pmapp/index.html'

    # テンプレートに変数を渡すメソッド
    def get_context_data(self, **kwargs):
        # 自分の内容を継承してそのままcontextとして取得
        # 一旦TemplateViewの中で記述するのが決まり事
        # 継承元のメソッドを呼び出すおまじない
        context = super().get_context_data(**kwargs)
        # postというテーブルの中から全て取得
        # Post.objects  テーブル名.objectsは決まり事
        post_list = Post.objects.all().order_by('-created_at')
        # 辞書　key： value
        context = {
            'post_list': post_list,
        }
        # HTMLに渡すパラメータ
        return context

# それぞれのViewが持つ機能を引き継ぐ（継承）ので、記述がシンプルになる
# ログイン時のみ作成できるようにする
# 　→ ログインしていないと、新規投稿ボタンを押してもログイン画面に飛ばされる（　LoginRequiredMixinにより実装　＊クラスベースビュー）
# 注意！　 LoginRequiredMixinは、 CreateViewよりも前に書く。　Mixinというのは多重継承
class PostCreate(LoginRequiredMixin, CreateView):
    # Postのモデルを作る
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('pmapp:index')

    # formの内容が正しい時　（タイトルに何も入っていない場合などはエラー）
    def form_valid(self, form):
        post = form.save(commit=False)
        tag = form.cleaned_data.get("tag")
        # ログイン中のユーザーをセットするための記述
        form.instance.author_id = self.request.user.id
        if tag:
            post.tag, created = Tags.objects.get_or_create(name=tag)
        post.save() # 一旦save
        # PostCreateの内容を上書き formそのものを返す記述
        return super(PostCreate, self).form_valid(form)

    #Postを作成できたら、メッセージを表示
    def get_success_url(self):
        messages.success(self.request, 'Postを登録しました。')
        return resolve_url('pmapp:index')

# 投稿詳細
class PostDetail(DetailView):
    # 取得した内容はHTMLでobjectとして渡される。　（Djangoでは、DetailViewを使った場合このような処理になる）
    model = Post
    template_name = 'pmapp/post_detail.html'

    # コメントを渡す
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        # テンプレートにコメント作成フォームを渡す
        context['comment_form'] = CommentCreateForm

        # 自分自身のデータを取得  一つ以上必ずデータを取得
        detail_data = Post.objects.get(id = self.kwargs['pk'])
        # 同じカテゴリに属する記事をとってくる処理  最新５件だけとってくる
        # Postの中にcategoryは存在する。detail_data.category
        category_posts = Post.objects.filter(category = detail_data.category).order_by('-created_at')[:5]
        # 'category_post'：キー, category_posts: value
        context['category_post'] = category_posts

        return context

# 更新
class PostUpdate(OnlyMyPostMixin, UpdateView):
    # テーブル名
    model = Post
    # forms.pyで書いたクラス名
    form_class = PostForm

    # 更新ボタンを押した後の処理
    def get_success_url(self):
        # ここでメッセージの色を変えることができる。　infoが青
        messages.info(self.request, 'Postを更新しました。')
        # 更新した後に遷移するURL
        return resolve_url('pmapp:post_detail', pk=self.kwargs['pk'])

# 削除
# DeleteView Django特有の機能　Djangoのメリット　簡単に記述できる
# 本当に削除しますか？　という確認画面を作ってくれる
class PostDelete(OnlyMyPostMixin, DeleteView):
    model = Post

    # 削除ボタンを押した後の処理
    def get_success_url(self):
        # infoはbootstrapと連動
        messages.info(self.request, 'Postを削除しました。')
        # 削除した後に遷移するURL
        return resolve_url('pmapp:index')

# 投稿一覧クラス
class PostList(ListView):
    model = Post
    paginate_by = 5

# お気に入り一覧クラス
class LikeList(ListView):
    model = Like
    template_name = 'pmapp/like_list.html'
    # レコード情報をテンプレートに渡すオブジェクト
    context_object_name = "like_list"
    paginate_by = 5

# 曲一覧クラス
class MusicList(ListView):
    # このListを使いたいページをtemplate_nameで指定
    template_name = 'pmapp/music_list.html'
    model = Post
    paginate_by = 5

# アーティスト一覧クラス
class ArtistList(ListView):
    # このListを使いたいページをtemplate_nameで指定
    template_name = 'pmapp/artist_list.html'
    model = Post
    paginate_by = 5

# 写真一覧クラス
class PhotoList(ListView):
    # このListを使いたいページをtemplate_nameで指定
    template_name = 'pmapp/photo_list.html'
    model = Post
    paginate_by = 5

    # Djangoが用意してくれている関数
    def get_queryset(self):
        return Post.objects.all().order_by('-created_at')

class Login(LoginView):
    form_class = LoginForm
    # ログイン画面指定
    template_name = 'pmapp/login.html'

class Logout(LogoutView):
    template_name = 'pmapp/logout.html'

# Userを作るためCreateViewを使う
class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'pmapp/signup.html'
    success_url = reverse_lazy('pmapp:index')

    # formの内容にエラーがない場合に実行
    def form_valid(self, form):
        # formの内容を保存
        user = form.save()
        # 上で作ったユーザーを使ってログイン
        login(self.request, user)
        self.object = user
        messages.info(self.request, 'ユーザー登録をしました。')
        return HttpResponseRedirect(self.get_success_url())

@login_required
def Like_add(request, post_id):
    # クラスベースでは、勝手にこのidを取ってきてくれるが、関数ベースなので明示する必要あり
    post = Post.objects.get(id = post_id)
    # お気に入り登録した投稿の数をカウント  filterの中に抽出条件を入れる
    is_liked = Like.objects.filter(user = request.user, post = post_id).count()
    # １回でもお気に入りに追加していたら追加済みメッセージを表示
    if is_liked > 0:
        messages.info(request, 'すでにお気に入りに追加済みです。')
        # ページ遷移先
        return redirect ('pmapp:post_detail', post_id)

    like = Like()
    # request.userはログイン中のユーザー
    like.user = request.user
    like.post = post
    like.post_pk = post.id
    like.save()  #Likeにデータ保存

    messages.success(request, 'お気に入りに追加しました!')
    # 詳細ページでは、post.idを記載しないと、どの投稿の詳細ページかわからなくなるのでid指定
    return redirect('pmapp:post_detail', post.id)

# 検索結果一覧クラス
class SearchList(TemplateView):
    template_name = 'pmapp/search_form.html'
    # テンプレートに変数を渡すメソッド
    def get_context_data(self, **kwargs):
        # 自分の内容を継承してそのままcontextとして取得
        # 一旦TemplateViewの中で記述するのが決まり事
        # 継承元のメソッドを呼び出すおまじない
        context = super().get_context_data(**kwargs)
        # postというテーブルの中から全て取得
        # Post.objects  テーブル名.objectsは決まり事
        post_list = Post.objects.all().order_by('-created_at')
        # 辞書　key： value
        context = {
            'post_list': post_list,
        }
        # HTMLに渡すパラメータ
        return context

# カテゴリ一覧クラス
class CategoryList(ListView):
    model = Category

# カテゴリ詳細ページ
class CategoryDetail(DetailView):
    model = Category
    # この二つを記述しないとURLにすることはできない
    slug_field = 'name_en'
    slug_url_kwarg = 'name_en'

    def get_context_data(self, *args, **kwargs):
        detail_data = Category.objects.get(name_en = self.kwargs['name_en'])
        category_posts = Post.objects.filter(category = detail_data.id).order_by('-created_at')

        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }

        return params

# 検索関数
def Search(request):
    if request.method == 'POST':
        # freewordという空の箱を持った変数
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            # cleaned_data → エラーがないかチェック済みのデータ
            freeword = searchform.cleaned_data['freeword']
            #QはOR条件　　A OR B （　Q()｜Q ()）
            # title または contentsにfreewordがはいっているかどうか
            search_list = Post.objects.filter(Q(title__icontains = freeword) |Q(content__icontains = freeword)
            |Q(music_title__icontains = freeword)|Q(artist__icontains = freeword))

        params = {
            # Search.HTMLに渡す
            'search_list': search_list,
        }
        return render (request, 'pmapp/search.html', params)

# タグ新規作成クラス
class TagCreate(LoginRequiredMixin, CreateView):
    # Postのモデルを作る
    model = Tags
    form_class = TagsForm
    success_url = reverse_lazy('pmapp:post_create')

    # formの内容が正しい時　（タイトルに何も入っていない場合などはエラー）
    def form_valid(self, form):
        # ログイン中のユーザーをセットするための記述
        form.instance.author_id = self.request.user.id
        # PostCreateの内容を上書き formそのものを返す記述
        return super(TagCreate, self).form_valid(form)

    #Tagを作成できたら、メッセージを表示
    def get_success_url(self):
        messages.success(self.request, 'Tagを登録しました。')
        return resolve_url('pmapp:post_create')

class CommentCreate(generic.CreateView):
    """
    記事へのコメント作成ビュー
    ページは表示されないが、コメントを作成するために使用
    """
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        post_pk = self.kwargs.get('pk')
        post = get_object_or_404(Post, pk=post_pk)

        comment = form.save(commit=False)
        comment.target = post
        comment.save()

        return redirect('pmapp:post_detail', pk=post_pk)

#投稿した記事をカレンダーで表示
class MyCalendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.TemplateView):

pmapp/templates/pmapp/category_list.html
{% extends 'pmapp/base.html' %}

{% block content %}
<div class="row mb-5">
    <div class="col-md-9">
        <div class="jumbotron-fluid mb-4">
            <div class="container pt-5">
                <p class="lead">Category</p>
                <h2 class="display-4">カテゴリー</h2>
            </div>
        </div>
    </div>
    <div class="row">

        {% for category in category_list %}
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">
                        <a class="text-dark"
                            href="{% url 'pmapp:category_detail' category.name_en %}">{{ category.name }}</a>&nbsp;<small>[&nbsp;{{ category.post_count }}&nbsp;]</small>
                    </h4>
                    <hr>
                    <!-- __setはDjangoが用意しているもの -->
                    <!-- 組み込みタグ: 投稿は２件まで表示 slice:":5" -->
                    {% for post in category.post_set.all|slice:":5" %}
                    <p><a href="{% url 'pmapp:post_detail' post.id %}" style="color:black;">{{ post.title }}</a></p>
                    {% endfor %}
                    <br>
                    <a href="{% url 'pmapp:category_detail' category.name_en %}">このカテゴリーの記事を全て見る<i
                            class="fas fa-arrow-right"></i></a>
                </div>
            </div>
            <br>
        </div>
        {% endfor %}
    </div>
    <br>
    <a href="{% url 'pmapp:library' %}" class="btn btn-outline-dark mb-5">戻る</a>
    {% endblock %}

pmapp/templates/pmapp/like_list.html
{% extends 'pmapp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <div class="jumbotron-fluid m-5">
            <div class="container">
                <p class="lead">Like List</p>
                <h2 class="display-4">お気に入り一覧</h2>
            </div>
        </div>
        <h3>
            <span class="badge badge-success pt-3 pb-3 pl-4 pr-4 mr-2">{{ request.user }}</span></h3>
        </h3>

        <table class="table">
            <thead>
                <tr>
                    <th width="200px">
                        <h4 class="font-weight-bold">タイトル</h4>
                    </th>
                </tr>
            </thead>
            <tbody>
                <!-- ListViewの場合は、モデル名_listで、そのクラスで指定したリストが渡される。 -->
                {% for item in like_list %}
                <tr>
                    <td><a href="{% url 'pmapp:post_detail' item.post_pk %}">{{ item.post }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        {% include 'pmapp/pagination.html' %}
        <br>
    </div>
</div>
<a href="{% url 'pmapp:mypage' %}" class="btn btn-outline-dark mb-5">戻る</a>
{% endblock %}

pmapp/templates/pmapp/post_detail.html
{% extends 'pmapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<!-- このページの描画がおかしい -->
<!-- 全部消してh1タグでaaaaとすると描画される -->

<!-- 詳細ページ -->
<div class="row mt-5">
    <div class="col-md-9">
        <br>
        <br>
        <div class="card">
            {% if object.thumbnail %}

            <img src="{{ object.thumbnail.url }}" class="card-img-top" alt="{{ object.title }}" />
            {% else %}
            <img src="https://mdbcdn.b-cdn.net/img/new/standard/nature/184.webp" class="card-img-top"
                alt="{{ object.title }}" />
            {% endif %}
            <!-- ここのobject.idの値がitem.idになっていたため、
            NoReverseMatch at /post_detail/14
            Reverse for 'post_detail' with arguments '('',)' not found.
            1 pattern(s) tried: ['post_detail/(?P<pk>[0-9]+)\\Z']
            エラーになってしまっていた。-->
            <a href="{% url 'pmapp:post_detail' object.id %}">
                <div class="mask rgba-whileslight"></div>
            </a>
            <div class="card-body">
                <!-- Title -->
                <!-- HTML内でデータベースからの値を表示する -->
                <!-- DetailViewの場合は、個別の値はobjectという変数に入ってHTMLに渡される -->
                <h2 class="card-title">{{ object.title }}</h2>
                <div class="d-flex flex-row">
                    <h5><span class="badge badge-info pt-2 mr-2">{{ object.category }}</span></h5>
                    <h5><span class="badge badge-success pt-2">{{ object.author }}</span></h5>
                    <h5><i class="fas fa-heart ml-4" style="color:pink;"></i>&nbsp{{ object.like_count }}</h5>
                </div>
                <!-- 組み込みタグ　　linebraksbr: 改行を反映させる -->
                <!-- 組み込みタグ　　urlize: テキスト内のURLとEmailアドレスをクリック可能なURLに変換する。 -->
                <h2 class="card-text border-bottom mb-5 mt-4">
                    {{ object.content | safe | linebreaksbr | urlize }}</h2>
                {% with object.youtube_url|slice:"-11:" as YOUTUBE1 %}
                <!-- <p>{{ YOUTUBE1 }}</p>  test-->
                {% with "https://www.youtube.com/embed/"|add:YOUTUBE1 as YOUTUBE2 %}
                <!-- <p>{{ YOUTUBE2 }}</p> -->

                <!-- youtube_urlがデータベースに保存されていたら表示する -->
                {% if object.youtube_url != '1' %}
                {% if object.youtube_url %}
                <iframe width="560" height="315" src="{{ YOUTUBE2 }}" title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen>
                </iframe>
                {% endif %}
                {% endif %}
                <!--1つめの変数YOUYUBE1の終わりタグ-->
                {% endwith %}
                <!--2つめの変数YOUYUBE2の終わりタグ-->
                {% endwith %}

                {% if object.music_title != 'music_title' %}
                <div class="d-flex flex-row mt-3">
                    <h3 class="card-title"><a><i class="fas fa-compact-disc mr-1"></i>『{{ object.music_title }}』</a>
                    </h3>
                    <h4><i class="fas fa-user mr-3"></i>{{ object.artist }}</h4>
                </div>
                {% endif %}
                <h5><span class="badge badge-danger">{{ object.genre }}</span></h5>

                {% if object.music %}
                <!--新規投稿する際に音楽ファイルをアップロードしていれば再生コントローラー表示-->
                <audio id=" media" src="{{ object.music.url }}" controls>
                </audio>
                {% endif %}
                <br>
                <div class="comment">
                    <h4><i class="far fa-comment mr-2"></i>コメント</h4>
                    <!-- クラス名_set.all コメント全て取得 -->
                    {% for comment in post.comment_set.all %}
                    <div class="comment-text">
                        <p class="border-bottom">{{ comment.text }}</p>
                    </div>
                    {% endfor %}
                </div>
                <div class="comment-form mb-3">
                    <h4 class="border">コメント投稿</h4>
                    <!-- コメント作成用のURLを渡す -->
                    <form action="{% url 'pmapp:comment_create' post.pk %}" method="post">
                        {% csrf_token %}
                        {{ comment_form }}
                        <div class="mt-3">
                            <button class="btn btn-warning text-dark" type="submit"><i
                                    class="fas fa-paper-plane mr-2 text-white"></i>送信</button>
                        </div>
                    </form>
                </div>

                <!-- お気に入り追加ボタン post.pkは、postのidを示す -->
                <a class="btn" href="{% url 'pmapp:like_add' object.pk %}"
                    style="background-color: #ff6699; color: white;">お気に入り</a>
                <hr>
                <!-- 戻るボタン 履歴を参照して一個前に戻ることができる　-->
                <a href="{% url 'pmapp:index' %}" class="btn btn-outline-dark mt-2">戻る</a>
                {% if object.author == request.user %}
                <!-- 更新ボタン -->
                <a href="{% url 'pmapp:post_update' object.pk %}" class="btn btn-primary">更新</a>
                <!-- 削除ボタン -->
                <a href="{% url 'pmapp:post_delete' object.pk %}" class="btn btn-danger">削除</a>
                {% endif %}
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ object.category }}</h5>
                <p>このカテゴリの他の記事</p>
            </div>
            <ul class="list-group">
                {% for item in category_post %}
                <li class="list-group-item"><a href="{% url 'pmapp:post_detail' item.id %}">
                        {{ item.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

</div>
{% endblock %}